# Generated by Django 6.0.2 on 2026-02-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='guest', max_length=100, verbose_name='ニックネーム'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='user',
            name='size',
            field=models.CharField(blank=True, choices=[('', '未設定'), ('70', '70'), ('80', '80'), ('90', '90'), ('95', '95'), ('100', '100'), ('110', '110'), ('120', '120'), ('130', '130'), ('140', '140'), ('150', '150'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('LL', 'LL'), ('XL', 'XL'), ('その他', 'その他')], default='', max_length=10, verbose_name='サイズ'),
        ),
    ]
