# Generated by Django 6.0.2 on 2026-03-01 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='child_images', verbose_name='プロフィール画像')),
                ('nickname', models.CharField(max_length=100, verbose_name='ニックネーム')),
                ('size', models.CharField(blank=True, choices=[('', '未設定'), ('70', '70'), ('80', '80'), ('90', '90'), ('95', '95'), ('100', '100'), ('110', '110'), ('120', '120'), ('130', '130'), ('140', '140'), ('150', '150'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('LL', 'LL'), ('XL', 'XL'), ('その他', 'その他')], default='', max_length=10, verbose_name='サイズ')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childlen', to='accounts.family')),
            ],
        ),
    ]
