# Generated by Django 6.0.2 on 2026-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='size',
            field=models.CharField(choices=[('', '未設定'), ('70', '70'), ('80', '80'), ('90', '90'), ('95', '95'), ('100', '100'), ('110', '110'), ('120', '120'), ('130', '130'), ('140', '140'), ('150', '150'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('LL', 'LL'), ('XL', 'XL'), ('その他', 'その他')], max_length=10, verbose_name='サイズ'),
        ),
    ]
