# Generated by Django 6.0.2 on 2026-03-23 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_child'),
        ('closet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_type', models.IntegerField(choices=[(0, 'internal'), (1, 'external')], verbose_name='コーデ種別')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='お気に入り')),
                ('external_url', models.URLField(blank=True, verbose_name='外部サイトURL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.child', verbose_name='子ども')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.clothingitem', verbose_name='洋服アイテム')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_clothing_items', to='cordinate.outfit', verbose_name='コーディネート')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_image', models.ImageField(upload_to='cordinate/', verbose_name='コーデ画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_images', to='cordinate.outfit', verbose_name='コーディネート')),
            ],
        ),
    ]
