# Generated by Django 6.0.2 on 2026-04-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_urls', to='cordinate.outfit')),
            ],
        ),
    ]
