# Generated by Django 6.0.2 on 2026-04-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_child'),
        ('cordinate', '0002_outfiturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.ImageField(choices=[(0, '持ち物'), (1, '必要な物')], upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursery_items', to='accounts.child')),
            ],
        ),
    ]
