# Generated by Django 6.0.2 on 2026-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordinate', '0003_nurseryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseryitem',
            name='item_type',
            field=models.IntegerField(choices=[(0, '持ち物'), (1, '必要な物')]),
        ),
    ]
