# Generated by Django 6.0.2 on 2026-03-10 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_child'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_image', models.ImageField(upload_to='clothing_photos/')),
                ('size', models.CharField(choices=[('', '未設定'), ('70', '70'), ('80', '80'), ('90', '90'), ('95', '95'), ('100', '100'), ('110', '110'), ('120', '120'), ('130', '130'), ('140', '140'), ('150', '150'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('LL', 'LL'), ('XL', 'XL'), ('その他', 'その他')], max_length=10)),
                ('color', models.CharField(choices=[('white', '白'), ('black', '黒'), ('navy', '紺'), ('brown', '茶'), ('beige', 'ベージュ'), ('gray', 'グレー'), ('khaki', 'カーキ'), ('green', '緑'), ('blue', '青'), ('red', '赤'), ('pink', 'ピンク'), ('purple', '紫'), ('yellow', '黄'), ('orange', 'オレンジ'), ('other', 'その他')], max_length=20)),
                ('wear_status', models.CharField(blank=True, choices=[('unused', '未使用'), ('justsize', 'ジャストサイズ'), ('large', '大きめ'), ('small', '小さめ'), ('rarely', 'あまり着ていない'), ('sizeout', 'サイズアウト')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='closet.category')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='accounts.child')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to=settings.AUTH_USER_MODEL)),
                ('seasons', models.ManyToManyField(related_name='clothes', to='closet.season')),
            ],
        ),
    ]
