# Generated by Django 6.0.2 on 2026-04-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_child'),
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.family'),
        ),
    ]
