# Generated by Django 6.0.2 on 2026-06-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_alter_clothingitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
